name: build apk

env:
  main_project_module: app

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current date
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name
        run: echo "repository_name=$(basename '${{ github.repository }}')" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
